### ISSUE TITLE
Linux - Signer stuck at loading

### ISSUE THREAD

**Issue by Tbaut** [Manta-Network/manta-signer#91] opened 2022-05-25 16:05 UTC
On v0.6.0, linux Mint. 
The signer interface is stuck on `Loading...` after launch
The first time I launched it after install I had the same issue. I deleted the `~/.config/manta-signer` and was then able to create an account. I had played with v0.5 in the past.
When I launch the signer subsequently though I have this issue.

When I launch it using the cli it only prints:
```
INFO  2022-05-25 15:58:29.940007352 UTC: performing service setup with Config {
    data_path: "/home/thib/.config/manta-signer/storage.dat",
    service_url: "127.0.0.1:29987",
    origin_url: Some(
        "https://app.dolphin.manta.network",
    ),
}
INFO  2022-05-25 15:58:29.940131435 UTC: building signer server
INFO  2022-05-25 15:58:29.940198402 UTC: loading latest parameters from Manta SDK
INFO  2022-05-25 15:58:30.171731813 UTC: setting up configuration
INFO  2022-05-25 15:58:30.171878449 UTC: loading password from authorizer
```

**Comment by knopki** [comment] 2022-06-01 14:31
I confirm the bug. Account recovery is not implemented and therefore deleting a profile is painful. You can delete only `~/.config/manta-signer/sdk` - after that signer starts normally with old account.

**Comment by Kevingislason** [comment] 2022-08-11 04:49
Most likely duplicate of #146

**Comment by Tbaut** [comment] 2022-08-11 10:11
Would love to see some movement on this, I haven't been able to properly test dolphin v2 in months.

**Comment by stechu** [comment] 2022-08-15 18:02
> Would love to see some movement on this, I haven't been able to properly test dolphin v2 in months.

Working on that, should be fixed by the next release.

**Closed** 2022-08-24 21:50 UTC
Labels: C-bug, P-high
