### ISSUE TITLE
Manta signer always failing on Mac OS ( 1006:: Abnormal Closure)

### ISSUE THREAD

**Issue by IgorSmailov** [Manta-Network/manta-signer#92] opened 2022-05-26 16:06 UTC
Here an issue, I've added comment in discord, but seems to many spam messages there
You could directly contact if need more logs: Discord Smailov#6105

```
Unchecked runtime.lastError: The message port closed before a response was received.
logger.js:62 2022-05-26 18:44:56          API-WS: disconnected from wss://ford.rococo.dolphin.engineering: 1006:: Abnormal 
logger.js:62 2022-05-26 18:44:56        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: disconnected from wss://ford.rococo.dolphin.engineering: 1006:: Abnormal Closure

[app.dolphin.manta.network-1653580956715.log](https://github.com/Manta-Network/manta-signer/files/8780353/app.dolphin.manta.network-1653580956715.log)
logger.js:62 2022-05-26 18:44:56             DRR: disconnected from wss://ford.rococo.dolphin.engineering: 1006:: Abnormal Closure
11logger.js:62 2022-05-26 18:44:56        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: disconnected from wss://ford.rococo.dolphin.engineering: 1006:: Abnormal Closure
p @ logger.js:62
logger.js:62 2022-05-26 18:44:56        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: disconnected from wss://ford.rococo.dolphin.engineering: 1006:: Abnormal Closure
manta_wasm_wallet_bg.js:1658 panicked at 'unexpected exception: JsValue(Error: disconnected from wss://ford.rococo.dolphin.engineering: 1006:: Abnormal Closure
Error: disconnected from wss://ford.rococo.dolphin.engineering: 1006:: Abnormal Closure
    at WebSocket.value (https://app.dolphin.manta.network/static/js/2.72b5b368.chunk.js:2:4307789))', src/lib.rs:54:1

Stack:
Error
    at Object.Lt (https://app.dolphin.manta.network/static/js/3.3704a37c.chunk.js:1:14305)
    at __wbg_new_693216e109162396 (https://app.dolphin.manta.network/:1:4710)

Promise.then (async)
Tt @ manta_wasm_wallet_bg.js:1561

index.js:169 Uncaught (in promise) Error: disconnected from wss://ford.rococo.dolphin.engineering: 1006:: Abnormal Closure
    at WebSocket.value (index.js:169:23)

c42e1e8fb5c37a361ce5.module.wasm:0x7325d Uncaught (in promise) RuntimeError: unreachable

```

**Comment by IgorSmailov** [comment] 2022-05-26 16:06
<img width="1760" alt="Screenshot 2022-05-26 at 19 06 21" src="https://user-images.githubusercontent.com/23527244/170528045-b61b451c-2b7d-4e1f-a292-01f62bf78e83.png">

**Comment by IgorSmailov** [comment] 2022-05-26 16:20
[app.dolphin.manta.network-1653580956715.log](https://github.com/Manta-Network/manta-signer/files/8780478/app.dolphin.manta.network-1653580956715.log)

**Comment by bhgomes** [comment] 2022-06-02 02:20
@IgorSmailov have you tried it in the last few days? We have updated the Dolphin nodes to make it easier to connect to.

**Comment by IgorSmailov** [comment] 2022-06-02 07:08
> @IgorSmailov have you tried it in the last few days? We have updated the Dolphin nodes to make it easier to connect to.

Sure, will check it today

**Comment by Kevingislason** [comment] 2022-06-13 18:13
This seems to be fixed on the front end, please reopen if you can still reproduce

**Closed by Kevingislason** 2022-06-13 18:13 UTC
